<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>protolist</string>
	</array>
	<key>name</key>
	<string>protolist</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#package</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\#</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.block.protolist</string>
				</dict>
			</array>
		</dict>
		<key>package</key>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9_]*)(\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.protolist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#proto</string>
				</dict>
			</array>
		</dict>
		<key>proto</key>
		<dict>
			<key>begin</key>
			<string>([A-Za-z][A-Za-z0-9_]*)(\s*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.type.protolist</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$\n?</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.protolist</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.protolist</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(:\[((\.([A-Za-z][A-Za-z0-9_]*))*)\])?(\s*)=(\s*)([0-9]+)</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.protolist</string>
	<key>uuid</key>
	<string>aeca2548-2611-4aae-8132-97631f3e48db</string>
</dict>
</plist>
